//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZombieStandardTime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZombieStandardTime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch State of Decay. Please verify that you are running Zombie Standard Time as an Administrator..
        /// </summary>
        internal static string GameLaunchFailed {
            get {
                return ResourceManager.GetString("GameLaunchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to StateOfDecay.exe is invalid. Please verify the path to the game executable below..
        /// </summary>
        internal static string PathToGameInvalid {
            get {
                return ResourceManager.GetString("PathToGameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup of userdata folder failed. Please verify that you have the correct permissions and the target disk is not full..
        /// </summary>
        internal static string PathToUserDataBackupInvalid {
            get {
                return ResourceManager.GetString("PathToUserDataBackupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to your userdata folder is invalid. Please verify the path below. If this is the first time you&apos;ve played State of Decay, please run State of Decay one time without Zombie Standard Time; this will create the required userdata folder..
        /// </summary>
        internal static string PathToUserDataInvalid {
            get {
                return ResourceManager.GetString("PathToUserDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update adjusted times for Last Played date. This may cause inconistencies with time offset calculations the next time you play. Please verify that you have the correct permissions and the target disk is not full..
        /// </summary>
        internal static string PostLaunchFileUpdateFailed {
            get {
                return ResourceManager.GetString("PostLaunchFileUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate your Steam profile. Please close and restart Zombie Standard Time..
        /// </summary>
        internal static string ProfileIsNull {
            get {
                return ResourceManager.GetString("ProfileIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of Decay still running.
        /// </summary>
        internal static string StateOfDecayStillRunningCaption {
            get {
                return ResourceManager.GetString("StateOfDecayStillRunningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of Decay is still running. Closing Zombie Standard Time may cause instability or savegame timing issues. Are you sure you want to close Zombie Standard Time?.
        /// </summary>
        internal static string StateOfDecayStillRunningMessage {
            get {
                return ResourceManager.GetString("StateOfDecayStillRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of Decay launched successfully..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occured launching State of Decay. Please verify the path to the game executable and the path to your userdata folder below..
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring your previous save game failed. Please verify that you have valid backups to restore and that the target disk is not full..
        /// </summary>
        internal static string UserDataRestoreFailed {
            get {
                return ResourceManager.GetString("UserDataRestoreFailed", resourceCulture);
            }
        }
    }
}
